# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51ba9422208449df8cd893c7832bb472467b985b14182e8b3bc7eced759533d8eb3c665b22c04b4ff2ab62bce75885357b5520f9555dce52c8166a939e3809e1

test:
  secret_key_base: 56cc5ac836663a9ee97c2c7e7ae6d47ac173531546badc1713275e69b99bc034c97a44d15891a431a9be64ff1dbeb6e21804c52b5317ad153fdb0d2444989ffe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
